//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystemApp.Model.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassedTests
    {
        public int id { get; set; }
        public int id_test { get; set; }
        public int id_user { get; set; }
        public double result { get; set; }
        public int time_spent_sec { get; set; }
        public double score { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Tests Tests { get; set; }
        public virtual Users Users { get; set; }
    }
}
