//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystemApp.Model.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int id { get; set; }
        public int test_id { get; set; }
        public int number { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public string answer_v1 { get; set; }
        public string answer_v2 { get; set; }
        public string answer_v3 { get; set; }
    
        public virtual Tests Tests { get; set; }
    }
}
